name = "Schmarrn Pack"
author = "andi_makes"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26e5b6ae331502d657869362cc2741409490fd054ea41ba2178102c42d75bc62"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
