name = "Schmarrn Pack"
author = "andi_makes"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "320e5b52367c52ead5d4f1d2f02b255d3b31850067aa13f32864edb75b59a3b2"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
