name = "Schmarrn Pack"
author = "andi_makes"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d6d4ee5f7ea36810482f53b50b7f8960cb5cd2498371e5dbba7797f11c175b0"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
