name = "Schmarrn Pack"
author = "andi_makes"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5957b54860f9ece1f214ac046d7e8af75404c3df839f421941cf19e69fd581c3"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
