name = "Schmarrn Pack"
author = "andi_makes"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e4ade47abe1019723f4312dbd466aba94bfc4d3d0bd7e7b16f91c39a707378d"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
