name = "Schmarrn Pack"
author = "andi_makes"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb26bc8aabd2df53b068ed04f10ed33f162ee0b673f18c9073c3ef6f2694ce6a"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
