name = "Schmarrn Pack"
author = "andi_makes"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caa4321d748f60705dfbdb5d0c68df1a5bd72222a208522a569592277191ae48"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
