name = "Schmarrn Pack"
author = "andi_makes"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd37a9cf192ca45771ca7f32e759641757c0602ef02dde8f665cdca6705a5445"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
