name = "Schmarrn Pack"
author = "andi_makes"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e48822231c80975eca5137a6c49e5eef2bbf5ed0aaa2d421a88a3b2833fabf26"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
