name = "Schmarrn Pack"
author = "andi_makes"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e727917228f1bab9e59fcb39f5fc5d4ce2fbb1c2ea62ac7906995fefdd4e732f"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1"]
